### ISSUE TITLE
Add search to leaderboard so you can search for yourself

### ISSUE THREAD

**Issue by whitep4nth3r** [whitep4nth3r/pantherworld#32]

**Comment by whitep4nth3r** [comment]
Might not be needed, given you are highlighted in the table.

**Comment by yoshivb** [comment]
It might still be nice to have a search option for the leaderboard so you can find other players, but probably not as critical since I would say that a browser's native search should mostly cover this already.

Also to add to this: I think if we do add a search option, it should behave like the native browser search, so not filter the leaderboard entries but just highlight and scroll to all the matching results one by one.

It might still be interesting to add sorting options to the leaderboard.
I'll create another issue for this.

**Comment by yoshivb** [comment]
@whitep4nth3r So this needs your input, if we are happy with the Search feature to be a "filter" so it only shows the row of your user, then this PR does that.

But if we want it more like a "Highlight and scroll to" Search then this does not.

**Comment by whitep4nth3r** [comment]
Yeah, I think a "highlight and scroll to" is what we want, because we want to be able to see a player's position in context to other player positions.

**Comment by whitep4nth3r** [comment]
> Are we planning to add pagination to the leaderboard anytime?

Not sure... it might over-complicate things.
